language: node_js
env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/shoe_catalogue_tests

node_js:
  - "v10.16.0"

services:
  - postgresql

before_script:
  - psql -c 'create database  shoe_catalogue_tests;' -U postgres
  - psql -U postgres -d shoe_catalogue_tests -a -f database/table.sql

after_success: npm run coverage

addons:
  apt:
    packages:
      - postgresql-server-dev-9.2